### ISSUE TITLE
docker run error passing config

### ISSUE THREAD

**Issue by suncarver** [sfudeus/docker_rctmon#3]
Hi,

I'm trying to use docker_rctmon on my Raspi 4, but I struggle already with first steps.

If I run

pi@Raspi7:~/IOTstack $ docker run -it --rm -c $configFile:/config.yaml -p 9831:9831 sfudeus/rctmon:latest

I get the following error:

invalid argument ":/config.yaml" for "-c, --cpu-shares" flag: strconv.ParseInt: parsing ":/config.yaml": invalid syntax
See 'docker run --help'.

How can I pass config.yaml as arg to the container?

Thanks for hints, Michael

**Comment by sfudeus** [comment]
Oh, my bad in the example.  It is `-v`, will fix that.

**Comment by suncarver** [comment]
Thanks for the quick response!

Not sure if I understand the -v. Tried -v instead of -c:

pi@Raspi7:~/IOTstack $ docker run -it --rm -v $configFile:/config.yaml -p 9831:9831 sfudeus/rctmon:latest
Usage: rctmon [OPTIONS] COMMAND [ARGS]...
Try 'rctmon --help' for help.

Error: Invalid value for '-c' / '--config': '/config.yaml': No such file or directory

Could you please post the whole docker run command and clarify where the config.yaml is to be located? Also - what should the $configFile setting be?

Thanks, Michael

**Comment by sfudeus** [comment]
Ah, sorry for the too short explanation, I was only answering from my phone. 
I fixed the Readme by now. 

`-v` is the correct flag for mounting a `volume`, but the local source must be a absolute file path. 
So you might want to use something like 

```
docker run -it --rm -v $(pwd)/config.yaml:/config.yaml -p 9831:9831 sfudeus/rctmon:latest
```

which would expect a working config.yaml in your current working directory. 

Of course you can use any absolute path (e.g. `/etc/rctmon/config.yaml`), with
```
docker run -it --rm -v /etc/rctmon/config.yaml:/config.yaml -p 9831:9831 sfudeus/rctmon:latest
```

If you need additional help, don't hesitate to ask.

**Comment by suncarver** [comment]
You solved my issue - thanks Stephan!

**Comment by suncarver** [comment]
Closed issue
