### ISSUE TITLE
Docker hub typo in docker command

### ISSUE THREAD

**Issue by poggenpower** [sfudeus/docker_rctmon#8]
![image](https://github.com/sfudeus/docker_rctmon/assets/6035034/65012396-7c67-4c2f-9f9b-b74fe25933d1)
this must be `-v` and not `-c`. Here at git hub the command is shown correct. 

Bye
 Thomas

**Comment by sfudeus** [comment]
lol, of course. It is the config, but of course a mounted volume :-). I should even add $(pwd) or mention that $configFile must be an absolute path.

**Comment by sfudeus** [comment]
fixed as it already was in the git repo, thx for reporting.
